spring.datasource.url=jdbc:postgresql://ep-winter-block-aopq2juh-pooler.c-2.ap-southeast-1.aws.neon.tech/SpendWise?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FQZCJM8sdp2v
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=dev@localhost
logging.level.org.hibernate=INFO
jwt.secret=dev-local-secret-key-change-this-32chars-min
jwt.expiration=86400000
server.port=8090
